import { expect, test } from "@playwright/test";

test("solver runs and displays strategy metrics", async ({ page }) => {
  await page.goto("/solver");
  await expect(page.getByRole("button", { name: "Cancel" })).toBeDisabled();
  await expect(page.getByText("Memory estimate:")).toBeVisible();
  await page.getByLabel("Board").fill("Ah Ah Kd");
  await expect(page.getByRole("alert")).toContainText("duplicate");
  await expect(page.getByRole("button", { name: "Start solve" })).toBeDisabled();
  await page.getByLabel("Board").fill("Ah Kd");
  await expect(page.getByRole("alert")).toContainText("empty, flop, turn, or river");
  await expect(page.getByRole("button", { name: "Start solve" })).toBeDisabled();
  await page.getByLabel("Board").fill("Ah Kd 7c");
  await page.getByRole("button", { name: "Monotone" }).click();
  await expect(page.getByLabel("Board")).toHaveValue("As Ks 7s");
  await page.getByRole("button", { name: "Paired" }).click();
  await expect(page.getByLabel("Board")).toHaveValue("Ah Ad 7c");
  await page.getByRole("button", { name: "Random flop" }).click();
  await expect(page.getByLabel("Board")).toHaveValue(/^[2-9TJQKA][cdhs] [2-9TJQKA][cdhs] [2-9TJQKA][cdhs]$/);
  await page.getByLabel("Board").fill("Ah Kd 7c");
  await page.getByRole("button", { name: "Add Qs" }).click();
  await expect(page.getByLabel("Board")).toHaveValue("Ah Kd 7c Qs");
  await page.getByRole("button", { name: "Remove Qs" }).click();
  await expect(page.getByLabel("Board")).toHaveValue("Ah Kd 7c");
  await expect(page.getByLabel("Bet tree")).toContainText("flop 33,66,125,all-in");
  await page.getByLabel("Bet tree").fill("turn 66");
  await expect(page.getByRole("alert")).toContainText("bet tree");
  await expect(page.getByRole("button", { name: "Start solve" })).toBeDisabled();
  await page.getByLabel("Bet tree").fill("flop 33,66,125,all-in; turn 66,125,all-in; river 66,150,all-in");
  await page.getByRole("button", { name: "33% pot" }).click();
  await expect(page.getByLabel("Bet amount")).toHaveValue("33");
  await page.getByLabel("Board").fill("2c 3d 4h");
  await page.getByLabel("Game").selectOption("PLO5");
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText("AsAhKsKhQs");
  await expect(page.getByLabel("Hand class")).toContainText("AA double-suited");
  await expect(page.getByText("PLO Fast BR")).toBeVisible();
  await expect(page.getByText("PLO sample set")).toBeVisible();
  await expect(page.getByText("PLO iterations")).toBeVisible();
  await expect(page.getByText("PLO combo cap")).toBeVisible();
  await expect(page.getByText("PLO equity MC")).toBeVisible();
  await expect(page.getByText("PLO sampled proxy")).toBeVisible();
  await expect(page.getByText(/combo cap limits range representation/)).toBeVisible();
  await expect(page.getByText(/CFR iterations over the capped representative set/)).toBeVisible();
  await expect(page.getByText(/full external-sampling MCCFR.*still pending/)).toBeVisible();
  await page.getByLabel("Board").fill("As Kd 7c");
  await expect(page.getByRole("table", { name: "strategy table" })).not.toContainText("AsAhKsKhQs");
  await page.getByLabel("Board").fill("2c 3d 4h");
  await page.getByLabel("Game").selectOption("PLO4");
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText("AsAhKsKh");
  await expect(page.getByText("PLO Fast BR")).toBeVisible();
  await page.getByLabel("Game").selectOption("NLH");
  await page.getByLabel("Hero position").selectOption("CO");
  await page.getByLabel("Villain position").selectOption("BB");
  await page.getByLabel("Pot type").selectOption("3bet");
  await page.getByLabel("Precision").selectOption("precise");
  await page.getByLabel("Rake %").fill("5");
  await page.getByLabel("Rake cap").fill("10");
  await page.getByLabel("Hero range").fill("QQ, JTs");
  await page.getByLabel("Villain range").fill("AA, KQs");
  await page.getByRole("button", { name: "Start solve" }).click();
  await expect(page.getByRole("button", { name: "Cancel" })).toBeEnabled();
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText(/QcQd|JsTs/);
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText("R EV");
  await expect(page.getByLabel("Hand class")).toContainText("pair");
  await page.getByLabel("Hand class").selectOption("pair");
  await expect(page.getByText("MDF")).toBeVisible();
  await expect(page.getByText("SPR")).toBeVisible();
  await expect(page.getByText("BR gap")).toBeVisible();
  await expect(page.getByText("Range EV")).toBeVisible();
  await expect(page.getByText("Blockers")).toBeVisible();
  await expect(page.getByText("Info sets")).toBeVisible();
  await expect(page.getByText("Action mix")).toBeVisible();
  await expect(page.getByText("Action composition")).toBeVisible();
  await expect(page.getByText("Raise sizes", { exact: true })).toBeVisible();
  await expect(page.locator('[aria-label^="Raise sizes:"]')).toContainText("bb");
  await expect(page.getByLabel("solve nodes")).toContainText("root/call");
  await expect(page.getByLabel("solve nodes")).toContainText("root/raise-sizes");
  await expect(page.getByLabel("solve nodes")).toContainText("root/bet-33");
  await expect(page.getByLabel("solve nodes")).toContainText("root/bet-33/call");
  await page.getByRole("button", { name: /RAISE SIZES \(root\/raise-sizes/ }).click();
  await expect(page.getByText("Node: root/raise-sizes")).toBeVisible();
  await expect(page.getByText(/Tables:\s*raise-sizes\s*\/\s*raise-sizes/)).toBeVisible();
  await expect(page.getByRole("table", { name: "strategy table" }).getByRole("columnheader", { name: "all-in" })).toBeVisible();
  await page.getByRole("button", { name: /CALL \(root\/call/ }).click();
  await expect(page.getByText("Node: root/call")).toBeVisible();
  await expect(page.getByText("Info set: flop:root/call")).toBeVisible();
  await expect(page.getByText(/Tables:\s*terminal\s*\/\s*action:call/)).toBeVisible();
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText("100%");
  await page.getByRole("button", { name: /BET 33 \(root\/bet-33/ }).click();
  await expect(page.getByText("Node: root/bet-33")).toBeVisible();
  await page.getByRole("button", { name: /CALL \(root\/bet-33\/call/ }).click();
  await expect(page.getByText("Node: root/bet-33/call")).toBeVisible();
  await expect(page.getByText(/Tables:\s*terminal\s*\/\s*response:root\/bet-33\/call/)).toBeVisible();
  await expect(page.getByRole("table", { name: "strategy table" })).toContainText("100%");
  const responseCallRow = page.getByRole("table", { name: "strategy table" }).locator("tbody tr").first();
  await expect(responseCallRow.locator("td").nth(4)).toHaveText("0%");
  await expect(responseCallRow.locator("td").nth(5)).toHaveText("100%");
  await expect(responseCallRow.locator("td").nth(6)).toHaveText("0%");
  await expect(responseCallRow.locator("td").nth(8)).toHaveText("0.000");
  await expect(responseCallRow.locator("td").nth(10)).toHaveText("0.000");
  await expect(page.getByText("abstracted")).toBeVisible();
  await expect(page.getByText(/compact range abstraction/)).toBeVisible();
  await expect(page).toHaveURL(/spot=/);
  await expect(page.getByRole("button", { name: "Cancel" })).toBeDisabled();
  await page.getByRole("button", { name: "Start solve" }).click();
  await expect(page.getByText("cached")).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Bet tree")).toContainText("flop 33,66,125,all-in");
  await expect(page.getByLabel("Hero position")).toHaveValue("CO");
  await expect(page.getByLabel("Pot type")).toHaveValue("3bet");
  await expect(page.getByLabel("Precision")).toHaveValue("precise");
  await expect(page.getByLabel("Hero range")).toHaveValue("QQ, JTs");
  await expect(page.getByLabel("Villain range")).toHaveValue("AA, KQs");
});

test("equity lab shows AA vs KK", async ({ page }) => {
  await page.goto("/equity");
  await expect(page.locator(".card").filter({ hasText: "Player 1" })).toBeVisible();
  await expect(page.locator('[aria-label^="Player 1:"]')).toContainText(/Eq 8[0-3]\./);
  await expect(page.locator('[aria-label^="Player 1:"]')).toContainText("W");
  await expect(page.locator('[aria-label^="Player 1:"]')).toContainText("T");
  await expect(page.getByText(/Auto: Exact|Auto: MC/)).toBeVisible();
  await expect(page.getByLabel("Player 1 hand distribution")).toContainText("Pair");
  await page.getByLabel("Mode").selectOption("mc");
  await page.getByLabel("Iterations").fill("1000");
  await expect(page.locator('[aria-label^="Player 1:"]')).toContainText("±");
  await page.getByLabel("Dead cards example Ac Td").fill("As");
  await expect(page.getByRole("alert")).toContainText("duplicate");
  await page.getByLabel("Dead cards example Ac Td").fill("");
  await page.getByLabel("Board cards example Ah Kd 7c").fill("2c 3d 4h 5s 9c");
  await page.getByRole("button", { name: "Add player" }).click();
  await expect(page.locator('[aria-label^="Player 3:"]')).toBeVisible();
  await page.getByRole("button", { name: "Remove player" }).click();
  await page.getByLabel("Game").selectOption("PLO5");
  await expect(page.getByRole("alert")).toContainText("PLO5");
  await page.getByLabel("Player 1").fill("As Ah Kc Qd Js");
  await page.getByLabel("Player 2").fill("Ts 9h 8d 7c 6s");
  await expect(page.getByRole("alert")).toHaveCount(0);
  await expect(page.locator('[aria-label^="Player 2:"]')).toBeVisible();
});

test("range explorer shows PLO category search and list", async ({ page }) => {
  await page.goto("/range");
  await page.getByLabel("Game").selectOption("PLO");
  await expect(page.getByLabel("PLO category tree")).toContainText("AAxx");
  await expect(page.getByLabel("PLO hand list")).toContainText("AA**:ds");
  await page.getByRole("button", { name: /Rundowns/ }).click();
  await expect(page.getByLabel("PLO syntax search")).toHaveValue("JT98:ds@75");
  await expect(page.getByLabel("PLO hand list")).toContainText("75%");
  await page.getByLabel("PLO syntax search").fill("AA**:bad@50");
  await expect(page.getByRole("alert")).toContainText("suitedness");
});

test("trainer displays decision controls", async ({ page }) => {
  await page.goto("/trainer");
  await expect(page.getByText("BTN vs BB, SRP")).toBeVisible();
  await expect(page.locator('[aria-label="Street: flop"]')).toBeVisible();
  await expect(page.getByRole("button", { name: "Bet 66bb" })).toBeVisible();
  await expect(page.locator('[aria-label="Best size: Bet 66bb"]')).toBeVisible();
  await page.getByRole("button", { name: "Next drill" }).click();
  await expect(page.getByText("CO vs BB, SRP")).toBeVisible();
  await page.keyboard.press("B");
  await expect(page.locator('[aria-label="EV loss: 0.000bb"]')).toBeVisible();
  await expect(page.locator('[aria-label="Grade: Perfect"]')).toBeVisible();
  await expect(page.locator('[aria-label="Attempts: 1"]')).toBeVisible();
  await page.goto("/");
  await expect(page.locator('[aria-label^="Average EV loss:"]')).not.toContainText("No sessions");
});

test("range editor round trips text", async ({ page }) => {
  await page.goto("/editor");
  await page.getByLabel("Range text").fill("QQ, JTs:0.25");
  await expect(page.getByLabel("Range JSON")).toContainText('"text": "QQ, JTs:0.25"');
  await page.getByLabel("Action layer").selectOption("call");
  await page.getByLabel("Range text").fill("KQs");
  await expect(page.getByLabel("Range JSON")).toContainText('"call": "KQs"');
  await page.getByLabel("Action layer").selectOption("raise");
  await page.getByLabel("Range JSON").fill('{"version":1,"kind":"range","payload":{"text":"AA, KQs:0.5"}}');
  await page.getByRole("button", { name: "Import JSON" }).click();
  await expect(page.getByLabel("Range text")).toHaveValue("AA, KQs:0.5");
  await page.getByRole("button", { name: "Save" }).click();
  await expect(page.getByText("saved")).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Range text")).toHaveValue("AA, KQs:0.5");
});

test("COOP COEP headers are set", async ({ request }) => {
  const res = await request.get("/");
  expect(res.headers()["cross-origin-opener-policy"]).toBe("same-origin");
  expect(res.headers()["cross-origin-embedder-policy"]).toBe("require-corp");
});

test("top bar toggles theme and language", async ({ page }) => {
  await page.goto("/");
  await page.getByLabel("Toggle navigation").click();
  await expect(page.locator(".app")).toHaveClass(/collapsed/);
  await expect(page.locator(".nav-label", { hasText: "ダッシュボード" })).toBeHidden();
  await page.getByLabel("Toggle palette").click();
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  await page.getByLabel("Toggle language").click();
  await expect(page.getByLabel("Toggle language")).toHaveText("EN");
});

test("settings clears cached data", async ({ page }) => {
  await page.goto("/solver");
  await page.getByRole("button", { name: "Start solve" }).click();
  await expect(page.getByRole("button", { name: "Cancel" })).toBeDisabled();
  await page.goto("/settings");
  await page.getByLabel("Theme").selectOption("light");
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light");
  await page.getByLabel("Deck colors").selectOption("two");
  await expect(page.locator("html")).toHaveAttribute("data-deck", "two");
  await page.getByLabel("Precision").selectOption("precise");
  await expect(page.getByLabel("Precision")).toHaveValue("precise");
  await expect(page.locator(".card").filter({ hasText: /^Solves/ })).toBeVisible();
  await expect(page.getByLabel("Solve cache entries")).toBeVisible();
  await page.getByRole("button", { name: "Delete solve" }).click();
  await expect(page.locator('[aria-label="Solves: 0"]')).toBeVisible();
  await page.goto("/solver");
  await page.getByRole("button", { name: "Start solve" }).click();
  await expect(page.getByRole("button", { name: "Cancel" })).toBeDisabled();
  await page.goto("/settings");
  await page.getByRole("button", { name: "Clear all data" }).click();
  await expect(page.locator('[aria-label="Solves: 0"]')).toBeVisible();
});
