import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { engine } from "./index.js";

test("EngineAPI prefers generated wasm package when present", async () => {
  await engine.init();
  const backend = await engine.backend();
  if (existsSync(resolve("pkg/gto_lab_engine.js"))) assert.equal(backend, "wasm");
  const handle = await engine.solve(JSON.stringify({ pot: 100, bet: 66 }));
  const result = await engine.result(handle);
  assert.equal(result.nodes[0]?.id, "root");
  assert.equal(result.nodes[0]?.infoSet, "preflop:root");
  assert.equal(result.informationSets[0]?.key, "preflop:root");
  assert.equal(result.informationSets[0]?.strategyRef, "root");
  assert.ok(result.nodes.some((node) => node.id === "root/call"));
  assert.equal(result.rows[0]?.combo, "AcAd");
  assert.ok(Number.isFinite(result.rows[0]!.raiseEv));
  assert.equal(result.rows[0]!.bestRaiseAmount, 66);
  assert.ok(result.exploitability.length > 0);
  assert.equal(result.metrics.brGapPctPot, result.exploitability.at(-1)?.value);
  const rootStrategy = await engine.getStrategy(handle, "root");
  assert.equal(rootStrategy.combos[0], "AcAd");
  assert.equal(rootStrategy.actions.length, rootStrategy.combos.length * result.nodes[0]!.actions.length);
  assert.equal((await engine.getStrategy(handle, "root/call")).combos.length, 0);
  assert.equal((await engine.getStrategy(handle, "preflop:root/call")).combos.length, 0);
  const callMetrics = await engine.getHandMetrics(handle, "root/call");
  const callMetricsByInfoSet = await engine.getHandMetrics(handle, "preflop:root/call");
  assert.equal(callMetrics.ev.length, result.rows.length);
  assert.deepEqual([...callMetricsByInfoSet.ev], [...callMetrics.ev]);
  assert.ok(Math.abs(callMetrics.ev[0]! - result.rows[0]!.callEv) < 1e-6);
  assert.ok((callMetrics.equity[0] ?? 0) > 0);
  const betHandle = await engine.solve(JSON.stringify({ pot: 100, bet: 33, betTree: "flop 33" }));
  const betResult = await engine.result(betHandle);
  const betNode = betResult.nodes.find((node) => node.id === "root/bet-33")!;
  const betStrategy = await engine.getStrategy(betHandle, "root/bet-33");
  assert.equal(betStrategy.combos[0], "AcAd");
  assert.equal(betStrategy.actions.length, betStrategy.combos.length * betNode.actions.length);
  assert.ok(Math.abs(betStrategy.actions[0]! - 33 / 133) < 1e-12);
  const raiseSizeNode = betResult.nodes.find((node) => node.id === "root/raise-sizes")!;
  const raiseSizeStrategy = await engine.getStrategy(betHandle, "root/raise-sizes");
  assert.equal(raiseSizeStrategy.actions.length, raiseSizeStrategy.combos.length * raiseSizeNode.actions.length);
  assert.ok(Math.abs([...raiseSizeStrategy.actions.slice(0, raiseSizeNode.actions.length)].reduce((sum, value) => sum + value, 0) - betResult.rows[0]!.raise) < 1e-12);
  assert.equal(betResult.informationSets.find((infoSet) => infoSet.nodeId === "root/raise-sizes")?.strategyRef, "raise-sizes");
  const raiseSizeMetrics = await engine.getHandMetrics(betHandle, "root/raise-sizes");
  assert.equal(raiseSizeMetrics.ev.length, betStrategy.combos.length);
  assert.ok(Math.abs(raiseSizeMetrics.equity[0]! - betResult.rows[0]!.equity) < 1e-6);
  assert.ok(Number.isFinite(raiseSizeMetrics.ev[0]));
  const betMetrics = await engine.getHandMetrics(betHandle, "root/bet-33");
  assert.equal(betMetrics.ev.length, betStrategy.combos.length);
  assert.ok(Number.isFinite(betMetrics.ev[0]));
  assert.ok((betMetrics.equity[0] ?? 0) > 0);
  const betCallMetrics = await engine.getHandMetrics(betHandle, "root/bet-33/call");
  assert.equal(betCallMetrics.ev.length, betStrategy.combos.length);
  assert.ok(Number.isFinite(betCallMetrics.ev[0]));
  const betCallMetricsByInfoSet = await engine.getHandMetrics(betHandle, "preflop:root/bet-33/call");
  assert.deepEqual([...betCallMetricsByInfoSet.ev], [...betCallMetrics.ev]);
  const flopHandle = await engine.solve(JSON.stringify({ pot: 100, bet: 66, board: "Ah Kd 7c" }));
  const flopResult = await engine.result(flopHandle);
  assert.ok(flopResult.nodes.some((node) => node.id === "root/turn-low"));
  assert.equal(flopResult.informationSets.find((infoSet) => infoSet.nodeId === "root/turn-low")?.strategyRef, "root/turn-low");
  const turnBranchStrategy = await engine.getStrategy(flopHandle, "turn:root/turn-low");
  assert.equal(turnBranchStrategy.actions.length, turnBranchStrategy.combos.length * 3);
  const flopRootStrategy = await engine.getStrategy(flopHandle, "root");
  assert.notDeepEqual([...turnBranchStrategy.actions.slice(0, 3)], [...flopRootStrategy.actions.slice(0, 3)]);
  const plo4 = await engine.solve(JSON.stringify({ game: "PLO4", pot: 100, bet: 66 }));
  const plo4Result = await engine.result(plo4);
  assert.equal(plo4Result.rows[0]?.combo, "AsAhKsKh");
  assert.equal(plo4Result.rows[0]?.handClass, "AA double-suited");
  assert.ok((plo4Result.rows[0]?.blockedCombos ?? 0) > 0);
  assert.ok((plo4Result.metrics.brGapPctPot ?? -1) >= 0);
  assert.ok((plo4Result.metrics.ploFastExploitability ?? -1) >= 0);
  assert.equal(plo4Result.metrics.ploOpponentSampleCount, 6);
  assert.equal(plo4Result.metrics.ploOpponentWeightCoverage, 1);
  assert.equal(plo4Result.metrics.ploIterations, 2048);
  assert.equal(plo4Result.metrics.ploComboCap, 20000);
  assert.equal(plo4Result.metrics.ploEquitySamples, 512);
  const plo5 = await engine.solve(JSON.stringify({ game: "PLO5", pot: 100, bet: 66 }));
  const plo5Result = await engine.result(plo5);
  assert.equal(plo5Result.rows[0]?.combo, "AsAhKsKhQs");
  assert.ok((plo5Result.metrics.brGapPctPot ?? -1) >= 0);
  assert.ok((plo5Result.metrics.ploFastExploitability ?? -1) >= 0);
  assert.equal(plo5Result.metrics.ploOpponentSampleCount, 6);
  assert.equal(plo5Result.metrics.ploIterations, 2048);
  assert.equal(plo5Result.metrics.ploComboCap, 30000);
});
