import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { engine } from "./index.js";

test("EngineAPI prefers generated wasm package when present", async () => {
  await engine.init();
  const backend = await engine.backend();
  if (existsSync(resolve("pkg/gto_lab_engine.js"))) assert.equal(backend, "wasm");
  const handle = await engine.solve(JSON.stringify({ pot: 100, bet: 66 }));
  const result = await engine.result(handle);
  assert.equal(result.nodes[0]?.id, "root");
  assert.equal(result.nodes[0]?.infoSet, "preflop:root");
  assert.equal(result.informationSets[0]?.key, "preflop:root");
  assert.equal(result.informationSets[0]?.strategyRef, "root");
  assert.ok(result.nodes.some((node) => node.id === "root/call"));
  assert.equal(result.rows[0]?.combo, "AcAd");
  assert.ok(result.rows[0]!.raiseEv >= result.rows[0]!.callEv);
  assert.ok(result.exploitability.length > 0);
  assert.equal(result.metrics.brGapPctPot, result.exploitability.at(-1)?.value);
  assert.equal((await engine.getStrategy(handle, "root")).combos[0], "AcAd");
  assert.equal((await engine.getStrategy(handle, "root/call")).combos.length, 0);
  assert.equal((await engine.getStrategy(handle, "preflop:root/call")).combos.length, 0);
  const callMetrics = await engine.getHandMetrics(handle, "root/call");
  const callMetricsByInfoSet = await engine.getHandMetrics(handle, "preflop:root/call");
  assert.equal(callMetrics.ev.length, result.rows.length);
  assert.deepEqual([...callMetricsByInfoSet.ev], [...callMetrics.ev]);
  assert.ok(Math.abs(callMetrics.ev[0]! - result.rows[0]!.callEv) < 1e-6);
  assert.ok((callMetrics.equity[0] ?? 0) > 0);
  const betHandle = await engine.solve(JSON.stringify({ pot: 100, bet: 33, betTree: "flop 33" }));
  const betStrategy = await engine.getStrategy(betHandle, "root/bet-33");
  assert.equal(betStrategy.combos[0], "AcAd");
  assert.equal(betStrategy.actions.length, betStrategy.combos.length * 2);
  assert.ok(Math.abs(betStrategy.actions[0]! - 33 / 133) < 1e-12);
  const betMetrics = await engine.getHandMetrics(betHandle, "root/bet-33");
  assert.equal(betMetrics.ev.length, betStrategy.combos.length);
  assert.ok(Number.isFinite(betMetrics.ev[0]));
  assert.ok((betMetrics.equity[0] ?? 0) > 0);
  const plo4 = await engine.solve(JSON.stringify({ game: "PLO4", pot: 100, bet: 66 }));
  const plo4Result = await engine.result(plo4);
  assert.equal(plo4Result.rows[0]?.combo, "AsAhKsKh");
  assert.ok((plo4Result.metrics.brGapPctPot ?? -1) >= 0);
  assert.ok((plo4Result.metrics.ploFastExploitability ?? -1) >= 0);
  const plo5 = await engine.solve(JSON.stringify({ game: "PLO5", pot: 100, bet: 66 }));
  const plo5Result = await engine.result(plo5);
  assert.equal(plo5Result.rows[0]?.combo, "AsAhKsKhQs");
  assert.ok((plo5Result.metrics.brGapPctPot ?? -1) >= 0);
  assert.ok((plo5Result.metrics.ploFastExploitability ?? -1) >= 0);
});
